DRIVERDIR = $(ARCHDIR)/driver/
include $(DRIVERDIR)/Makefile

ARCH_OBJS = $(DRIVER_OBJS) \
$(ARCHDIR)/start.o \
$(ARCHDIR)/tty.o \
$(ARCHDIR)/paging.o \
$(ARCHDIR)/acpi.o \
$(ARCHDIR)/idt.o \
$(ARCHDIR)/isr_asm.o
