DRIVER_OBJS = $(DRIVERDIR)/pci.o \
$(DRIVERDIR)/disk/disk.o \
$(DRIVERDIR)/timer/timer.o \
$(DRIVERDIR)/timer/pit.o \
$(DRIVERDIR)/keyboard.o \
$(DRIVERDIR)/driver.o \
$(DRIVERDIR)/disk/ahci.o \
$(DRIVERDIR)/usb/usb.o
